"""create smtp_accounts table

Revision ID: bf6f691d350d
Revises: 28ca1c8e506b
Create Date: 2026-06-03 08:21:08.995253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6f691d350d'
down_revision: Union[str, Sequence[str], None] = '28ca1c8e506b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'failed', name='smtp_status_enum'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smtp_accounts_email'), 'smtp_accounts', ['email'], unique=False)
    op.create_index(op.f('ix_smtp_accounts_user_id'), 'smtp_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smtp_accounts_user_id'), table_name='smtp_accounts')
    op.drop_index(op.f('ix_smtp_accounts_email'), table_name='smtp_accounts')
    op.drop_table('smtp_accounts')
    # ### end Alembic commands ###
